/** Server-owned defaults for legacy records. Explicit empty values always win. */
const skillAssets = [['Java','java.jpg','#fff'],['Docker','docker.png','#57b6e6'],['Photoshop','photoshop.png','#4082c3'],['Node','node.svg','#333'],['Webpack','webpack.png','#2e3a41'],['Pinia','pinia.svg','#fff'],['Python','python.png','#fff'],['Vite','vite.svg','#937df7'],['Flutter','flutter.png','#4499e4'],['Vue','vue.png','#b8f0ae'],['React','','#222'],['CSS3','css3.png','#2c51db'],['JS','javascript.png','#f7cb4f'],['HTML','html.png','#e9572b'],['Git','git.webp','#df5b40'],['Apifox','apifox.png','#e65164']];
export const ABOUT_SECTIONS = ['intro','pursuit','hello','skills','careers','info','personality','photo','maxim','buff','game','comics','technology','music','cards','socials','donation','body'] as const;
export const ABOUT_TEXT_FIELDS = ['heading','subtitle','greeting','namePrefix','rolePrefix','pursuitLabel','pursuitTitle','helloText','skillsLabel','skillsTitle','careersLabel','careersTitle','locationPrefix','birthLabel','birthYearText','professionLabel','jobLabel','personalityLabel','personalityLinkText','mottoLabel','motto','buffLabel','buff','gameLabel','gameTitle','gameUid','comicsLabel','comicsTitle','technologyLabel','technologyTitle','technologyDescription','musicLabel','musicTitle','musicDescription','musicLinkText','donationTitle'];
export const ABOUT_URL_FIELDS = ['careersImage','mapDarkImage','avatar','personalityImage','personalityUrl','musicUrl'];
export function aboutMetadata(input: Record<string, any> = {}, site: Record<string, any> = {}, legacy = false, existing = false) {
  const empty = { ...Object.fromEntries(ABOUT_TEXT_FIELDS.map(key => [key, ''])), ...Object.fromEntries(ABOUT_URL_FIELDS.map(key => [key, ''])), name: '', role: '', location: '', career: '', profession: '', currentJob: '', personality: '', personalityCode: '', photo: '', mapImage: '', gameImage: '', technologyImage: '', musicImage: '', donationImage: '', donationText: '', profileTags: [], skills: [], skillItems: [], experiences: [], cards: [], socials: [], comics: [], pursuitWords: [], sections: Object.fromEntries(ABOUT_SECTIONS.map(key => [key, true])) };
  const defaults = { heading: '关于我', subtitle: '路虽远行则将至，事虽难则做必成✨', greeting: '你好，很高兴认识你👋', namePrefix: '我叫', rolePrefix: '是一名', pursuitLabel: '追求', pursuitTitle: '源于\n热爱而去 感受', pursuitWords: ['学习','生活','程序','体验'], helloText: 'Hello there!', skillsLabel: '技能', skillsTitle: '开启创造力', careersLabel: '生涯', careersTitle: '无限进步', locationPrefix: '我现在住在', birthLabel: '生于', professionLabel: '专业', jobLabel: '现在职业', personalityLabel: '性格', personalityLinkText: '了解更多关于我的性格', mottoLabel: '座右铭', motto: '路虽远行则将至，\n事虽难则做必成。', buffLabel: '特长', buff: '脑回路新奇的 酸菜鱼\n二次元指数 MAX', gameLabel: '爱好游戏', gameTitle: '原神', gameUid: 'UID: 125766904', comicsLabel: '爱好番剧', comicsTitle: '追番', technologyLabel: '关注偏好', technologyTitle: '数码科技', technologyDescription: '手机、电脑软硬件', musicLabel: '音乐偏好', musicTitle: '许嵩、民谣、华语流行', musicDescription: '跟 Tom 一起欣赏更多音乐', musicLinkText: '更多推荐', musicUrl: '/music/', donationTitle: '支持创作', avatar: site.avatar || '', name: 'Tom', role: '前端工程师', location: '中国,广州', career: 'EDU,软件工程专业', profession: '软件工程', currentJob: '社畜', personality: '执政官', personalityCode: 'ESFJ-A', personalityImage: 'https://npm.elemecdn.com/anzhiyu-blog@2.0.8/img/svg/ESFJ-A.svg', personalityUrl: 'https://www.16personalities.com/ch/esfj-人格', photo: site.heroImage || 'https://bu.dusays.com/2023/07/05/64a4c63495ac5.jpg', mapImage: site.heroImage || '', gameImage: 'https://bu.dusays.com/2023/04/22/64433bf26e25d.webp', technologyImage: 'https://bu.dusays.com/2022/12/06/638f5f05ce1f7.jpg', musicImage: 'https://p2.music.126.net/Mrg1i7DwcwjWBvQPIMt_Mg==/79164837213438.jpg', profileTags: ['🤖️ 数码科技爱好者','🔍 分享与热心帮助','🏠 智能家居小能手','🔨 设计开发一条龙','专修交互与设计 🤝','脚踏实地行动派 🏃','团队小组发动机 🧱','壮汉人狠话不多 💢'], comics: [
    {title:'约定的梦幻岛',image:'https://bu.dusays.com/2023/05/27/647166c44b414.webp',url:'https://www.bilibili.com/bangumi/media/md5267750/'},
    {title:'咒术回战',image:'https://bu.dusays.com/2023/05/24/646db4398832e.webp',url:'https://www.bilibili.com/bangumi/media/md28229899/'},
    {title:'紫罗兰永恒花园',image:'https://bu.dusays.com/2023/05/24/646db43983d99.webp',url:'https://www.bilibili.com/bangumi/media/md8892/'},
    {title:'鬼灭之刃',image:'https://bu.dusays.com/2023/05/24/646db439856a0.webp',url:'https://www.bilibili.com/bangumi/media/md22718131/'},
    {title:'JOJO的奇妙冒险 黄金之风',image:'https://bu.dusays.com/2023/05/30/64760e38d651a.webp',url:'https://www.bilibili.com/bangumi/media/md135652/'}] };
  const result: Record<string, any> = { ...empty, ...(legacy ? defaults : { heading: '关于我', donationTitle: '支持创作' }), ...(legacy || existing ? { careersImage: '/theme/about/careers.svg', birthYearText: '保密' } : {}), ...input };
  result.sections = { ...empty.sections, ...input.sections };
  if (!('skillItems' in input)) {
    const names = Array.isArray(input.skills) ? input.skills : legacy ? skillAssets.map(([name]) => name) : [];
    result.skillItems = names.map(name => { const asset = skillAssets.find(([label]) => label === name); return { name, image: asset?.[1] ? `/theme/skills/${asset[1]}` : '', color: asset?.[2] || '#f2f4ff' }; });
  }
  return result;
}
